<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Pages\Visitor\HomePageController;
use App\Http\Controllers\Pages\Visitor\SignInPageController;
use App\Http\Controllers\Pages\System\UserEditPageController;
use App\Http\Controllers\Pages\System\UsersListPageController;
use App\Http\Controllers\Pages\Author\MyNewsEditPageController;
use App\Http\Controllers\Pages\Author\MyNewsListPageController;
use App\Http\Controllers\Pages\Author\NewsCreatePageController;
use App\Http\Controllers\Pages\System\UserCreatePageController;
use App\Http\Controllers\Pages\System\UserDeletePageController;
use App\Http\Controllers\Pages\Visitor\NewsDetailPageController;
use App\Http\Controllers\Pages\Author\MyNewsDeletePageController;
use App\Http\Controllers\Pages\System\CategoryEditPageController;
use App\Http\Controllers\Pages\System\UserTypeEditPageController;
use App\Http\Controllers\Pages\System\UserTypesListPageController;
use App\Http\Controllers\Pages\Author\AuthorSettingsPageController;
use App\Http\Controllers\Pages\System\CategoriesListPageController;
use App\Http\Controllers\Pages\System\CategoryCreatePageController;
use App\Http\Controllers\Pages\System\CategoryDeletePageController;
use App\Http\Controllers\Pages\System\NewsStatisticsPageController;
use App\Http\Controllers\Pages\System\SystemNewsListPageController;
use App\Http\Controllers\Pages\System\SystemSettingsPageController;
use App\Http\Controllers\Pages\System\UserTypeCreatePageController;
use App\Http\Controllers\Pages\System\UserTypeDeletePageController;
use App\Http\Controllers\Pages\Author\AuthorDashboardPageController;
use App\Http\Controllers\Pages\System\SystemDashboardPageController;
use App\Http\Controllers\Pages\Author\MyNewsStatisticsPageController;
use App\Http\Controllers\Pages\System\CategoryTypeEditPageController;
use App\Http\Controllers\Pages\Visitor\VisitorNewsListPageController;
use App\Http\Controllers\Pages\System\CategoryGroupEditPageController;
use App\Http\Controllers\Pages\System\CategoryTypesListPageController;
use App\Http\Controllers\Pages\System\NewsStatisticTimePageController;
use App\Http\Controllers\Pages\System\CategoryGroupsListPageController;
use App\Http\Controllers\Pages\System\CategoryTypeCreatePageController;
use App\Http\Controllers\Pages\System\CategoryTypeDeletePageController;
use App\Http\Controllers\Pages\Author\MyNewsStatisticTimePageController;
use App\Http\Controllers\Pages\System\CategoryGroupCreatePageController;
use App\Http\Controllers\Pages\System\CategoryGroupDeletePageController;
use App\Http\Controllers\Pages\System\NewsStatisticDetailPageController;
use App\Http\Controllers\Pages\System\ResourcePlatformEditPageController;
use App\Http\Controllers\Pages\Author\MyNewsStatisticDetailPageController;
use App\Http\Controllers\Pages\System\ResourcePlatformsListPageController;
use App\Http\Controllers\Pages\System\ResourcePlatformCreatePageController;

/* VİSİTOR PAGES */

Route::get("/", [HomePageController::class, "index"]);
Route::get("/haberler/{listType}", [VisitorNewsListPageController::class, "index"]);
Route::get("haberler/yazar/{authorUserName}/{listType}", [VisitorNewsListPageController::class, "author"]);
Route::get("haberler/kategori/{categoryGroupLinkUrl}/{listType}", [VisitorNewsListPageController::class, "category"]);
Route::get("/haber/{newsLinkUrl}", [NewsDetailPageController::class, "index"]);
Route::get("/yazar-girisi", [SignInPageController::class, "index"]);

/* AUTHOR PAGES */
Route::get("/yazar-paneli", [AuthorDashboardPageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/yazar-paneli/haber/ekle", [NewsCreatePageController::class, "index"]);
Route::get("/yazar-paneli/haberlerim/{listType}", [MyNewsListPageController::class, "index"]);
Route::get("/yazar-paneli/haberlerim/duzenle/{newsNo}", [MyNewsEditPageController::class, "index"]);
Route::get("/yazar-paneli/haberlerim/sil/{newsNo}", [MyNewsDeletePageController::class, "index"]);
Route::get("/yazar-paneli/haberlerim/istatistikleri", [MyNewsStatisticsPageController::class, "index"]);
Route::get("/yazar-paneli/haberlerim/istatistikleri/zaman/{timeType}/{listType}", [MyNewsStatisticTimePageController::class, "index"]);
Route::get("/yazar-paneli/haberlerim/istatistikleri/detay/{newsNo}", [MyNewsStatisticDetailPageController::class, "index"]);
Route::get("/yazar-paneli/ayarlar/profilim", [AuthorSettingsPageController::class, "myAccount"]);
Route::get("/yazar-paneli/ayarlar/tema", [AuthorSettingsPageController::class, "theme"]);

/* SYSTEM PAGES */
Route::get("/sistem-paneli", [SystemDashboardPageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipi/ekle", [UserTypeCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipleri/", [UserTypesListPageController::class, "index"])->name("kullanici_tipleri");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipleri/no09", [UserTypesListPageController::class, "no09"])->name("kullanici_tipleri_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipleri/no90", [UserTypesListPageController::class, "no90"])->name("kullanici_tipleri_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipleri/nameAZ", [UserTypesListPageController::class, "nameAZ"])->name("kullanici_tipleri_nameAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipleri/nameZA", [UserTypesListPageController::class, "nameZA"])->name("kullanici_tipleri_nameZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici-tipi/düzenle/{no}", [UserTypeEditPageController::class, "index"])->name("kullanici_tipi_düzenle");
Route::get("/sistem-paneli/kullanici-tipi/sil/{no}", [UserTypeDeletePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanici/ekle", [UserCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/", [UsersListPageController::class, "index"])->name("kullanicilar");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/no09", [UsersListPageController::class, "no09"])->name("kullanicilar_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/no90", [UsersListPageController::class, "no90"])->name("kullanicilar_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/fullNameAZ", [UsersListPageController::class, "fullNameAZ"])->name("kullanicilar_fullNameAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/fullNameZA", [UsersListPageController::class, "fullNameZA"])->name("kullanicilar_fullNameZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/usernameAZ", [UsersListPageController::class, "usernameAZ"])->name("kullanicilar_usernameAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/usernameZA", [UsersListPageController::class, "usernameZA"])->name("kullanicilar_usernameZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/typeAZ", [UsersListPageController::class, "typeAZ"])->name("kullanicilar_typeAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kullanicilar/typeZA", [UsersListPageController::class, "typeZA"])->name("kullanicilar_typeZA");
Route::get("/sistem-paneli/kullanici/düzenle", [UserEditPageController::class, "index"]);
Route::get("/sistem-paneli/kullanici/sil", [UserDeletePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-site/ekle", [ResourcePlatformCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/", [ResourcePlatformsListPageController::class, "index"])->name("kaynak_siteler");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/no09", [ResourcePlatformsListPageController::class, "no09"])->name("kaynak_siteler_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/no90", [ResourcePlatformsListPageController::class, "no90"])->name("kaynak_siteler_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/nameAZ", [ResourcePlatformsListPageController::class, "nameAZ"])->name("kaynak_siteler_nameAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/nameZA", [ResourcePlatformsListPageController::class, "nameZA"])->name("kaynak_siteler_nameZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/websiteLinkAZ", [ResourcePlatformsListPageController::class, "websiteLinkAZ"])->name("kaynak_siteler_websiteLinkAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/websiteLinkZA", [ResourcePlatformsListPageController::class, "websiteLinkZA"])->name("kaynak_siteler_websiteLinkZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/linkUrlAZ", [ResourcePlatformsListPageController::class, "linkUrlAZ"])->name("kaynak_siteler_linkUrlAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kaynak-siteler/linkUrlZA", [ResourcePlatformsListPageController::class, "linkUrlZA"])->name("kaynak_siteler_linkUrlZA");
Route::get("/sistem-paneli/kaynak-site/düzenle", [ResourcePlatformEditPageController::class, "index"]);
Route::get("/sistem-paneli/kaynak-site/sil", [ResourcePlatformCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-tipi/ekle", [CategoryTypeCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-tipleri", [CategoryTypesListPageController::class, "index"])->name("kategori_tipleri");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-tipleri/no09", [CategoryTypesListPageController::class, "no09"])->name("kategori_tipleri_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-tipleri/no90", [CategoryTypesListPageController::class, "no90"])->name("kategori_tipleri_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-tipleri/nameAZ", [CategoryTypesListPageController::class, "nameAZ"])->name("kategori_tipleri_nameAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-tipleri/nameZA", [CategoryTypesListPageController::class, "nameZA"])->name("kategori_tipleri_nameZA");
Route::get("/sistem-paneli/kategori-tipi/düzenle", [CategoryTypeEditPageController::class, "index"]);
Route::get("/sistem-paneli/kategori-tipi/sil", [CategoryTypeDeletePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori/ekle", [CategoryCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler", [CategoriesListPageController::class, "index"])->name("kategoriler");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/no09", [CategoriesListPageController::class, "no09"])->name("kategoriler_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/no90", [CategoriesListPageController::class, "no90"])->name("kategoriler_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/nameAZ", [CategoriesListPageController::class, "nameAZ"])->name("kategoriler_nameAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/nameZA", [CategoriesListPageController::class, "nameZA"])->name("kategoriler_nameZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/typeAZ", [CategoriesListPageController::class, "typeAZ"])->name("kategoriler_typeAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/typeZA", [CategoriesListPageController::class, "typeZA"])->name("kategoriler_typeZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/mainCategoryAZ", [CategoriesListPageController::class, "mainCategoryAZ"])->name("kategoriler_mainCategoryAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/mainCategoryZA", [CategoriesListPageController::class, "mainCategoryZA"])->name("kategoriler_mainCategoryZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/linkUrlAZ", [CategoriesListPageController::class, "linkUrlAZ"])->name("kategoriler_linkUrlAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategoriler/linkUrlZA", [CategoriesListPageController::class, "linkUrlZA"])->name("kategoriler_linkUrlZA");
Route::get("/sistem-paneli/kategori/düzenle", [CategoryEditPageController::class, "index"]);
Route::get("/sistem-paneli/kategori/sil", [CategoryDeletePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-grubu/ekle", [CategoryGroupCreatePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/", [CategoryGroupsListPageController::class, "index"])->name("kategori_gruplari");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/no09", [CategoryGroupsListPageController::class, "no09"])->name("kategori_gruplari_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/no90", [CategoryGroupsListPageController::class, "no90"])->name("kategori_gruplari_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/mainAZ", [CategoryGroupsListPageController::class, "mainAZ"])->name("kategori_gruplari_mainAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/mainZA", [CategoryGroupsListPageController::class, "mainZA"])->name("kategori_gruplari_mainZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub1AZ", [CategoryGroupsListPageController::class, "sub1AZ"])->name("kategori_gruplari_sub1AZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub1ZA", [CategoryGroupsListPageController::class, "sub1ZA"])->name("kategori_gruplari_sub1ZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub2AZ", [CategoryGroupsListPageController::class, "sub2AZ"])->name("kategori_gruplari_sub2AZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub2ZA", [CategoryGroupsListPageController::class, "sub2ZA"])->name("kategori_gruplari_sub2ZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub3AZ", [CategoryGroupsListPageController::class, "sub3AZ"])->name("kategori_gruplari_sub3AZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub3ZA", [CategoryGroupsListPageController::class, "sub3ZA"])->name("kategori_gruplari_sub3ZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub4AZ", [CategoryGroupsListPageController::class, "sub4AZ"])->name("kategori_gruplari_sub4AZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub4ZA", [CategoryGroupsListPageController::class, "sub4ZA"])->name("kategori_gruplari_sub4ZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub5AZ", [CategoryGroupsListPageController::class, "sub5AZ"])->name("kategori_gruplari_sub5AZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/sub5ZA", [CategoryGroupsListPageController::class, "sub5ZA"])->name("kategori_gruplari_sub5ZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/linkUrlAZ", [CategoryGroupsListPageController::class, "linkUrlAZ"])->name("kategori_gruplari_linkUrlAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/kategori-gruplari/linkUrlZA", [CategoryGroupsListPageController::class, "linkUrlZA"])->name("kategori_gruplari_linkUrlZA");
Route::get("/sistem-paneli/kategori-grubu/düzenle", [CategoryGroupEditPageController::class, "index"]);
Route::get("/sistem-paneli/kategori-grubu/sil", [CategoryGroupDeletePageController::class, "index"]);
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler", [SystemNewsListPageController::class, "index"])->name("haberler");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/no09", [SystemNewsListPageController::class, "no09"])->name("haberler_no09");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/no90", [SystemNewsListPageController::class, "no90"])->name("haberler_no90");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/contentAZ", [SystemNewsListPageController::class, "contentAZ"])->name("haberler_contentAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/contentZA", [SystemNewsListPageController::class, "contentZA"])->name("haberler_contentZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/authorAZ", [SystemNewsListPageController::class, "authorAZ"])->name("haberler_authorAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/authorZA", [SystemNewsListPageController::class, "authorZA"])->name("haberler_authorZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/categoryAZ", [SystemNewsListPageController::class, "categoryAZ"])->name("haberler_categoryAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/categoryZA", [SystemNewsListPageController::class, "categoryZA"])->name("haberler_categoryZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/resourcePlatformAZ", [SystemNewsListPageController::class, "resourcePlatformAZ"])->name("haberler_resourcePlatformAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/resourcePlatformZA", [SystemNewsListPageController::class, "resourcePlatformZA"])->name("haberler_resourcePlatformZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/publishDateAZ", [SystemNewsListPageController::class, "publishDateAZ"])->name("haberler_publishDateAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/publishDateZA", [SystemNewsListPageController::class, "publishDateZA"])->name("haberler_publishDateZA");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/writeTimeAZ", [SystemNewsListPageController::class, "writeTimeAZ"])->name("haberler_writeTimeAZ");
/*TAMAMLANDI*/ //Route::get("/sistem-paneli/haberler/writeTimeZA", [SystemNewsListPageController::class, "writeTimeZA"])->name("haberler_writeTimeZA");
Route::get("/sistem-paneli/haberler/istatistikleri/{listType}", [NewsStatisticsPageController::class, "index"]);
Route::get("/sistem-paneli/haberler/istatistikleri/zaman/{timeType}/{listType}", [NewsStatisticTimePageController::class, "index"]);
Route::get("/sistem-paneli/haberler/istatistikleri/detay/{newsNo}", [NewsStatisticDetailPageController::class, "index"]);
Route::get("/sistem-paneli/ayarlar/tema", [SystemSettingsPageController::class, "theme"]);
Route::get("/sistem-paneli/ayarlar/sabitler", [SystemSettingsPageController::class, "constants"]);

/* SYSTEM PAGES FORM */
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici/ekle", [UserCreatePageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipi/ekle", [UserTypeCreatePageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-tipi/ekle", [CategoryTypeCreatePageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori/ekle", [CategoryCreatePageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-grubu/ekle", [CategoryGroupCreatePageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-site/ekle", [ResourcePlatformCreatePageController::class, "form"]);

/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipleri/", [UserTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipleri/no09", [UserTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipleri/no90", [UserTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipleri/nameAZ", [UserTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipleri/nameZA", [UserTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/no09", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/no90", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/fullNameAZ", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/fullNameZA", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/usernameAZ", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/usernameZA", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/typeAZ", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanicilar/typeZA", [UsersListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/no09", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/no90", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/nameAZ", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/nameZA", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/websiteLinkAZ", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/websiteLinkZA", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/linkUrlAZ", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kaynak-siteler/linkUrlZA", [ResourcePlatformsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-tipleri", [CategoryTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-tipleri/no09", [CategoryTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-tipleri/no90", [CategoryTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-tipleri/nameAZ", [CategoryTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-tipleri/nameZA", [CategoryTypesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/no09", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/no90", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/nameAZ", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/nameZA", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/typeAZ", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/typeZA", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/mainCategoryAZ", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/mainCategoryZA", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/linkUrlAZ", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategoriler/linkUrlZA", [CategoriesListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/no09", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/no90", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/mainAZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/mainZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub1AZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub1ZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub2AZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub2ZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub3AZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub3ZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub4AZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub4ZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub5AZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/sub5ZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/linkUrlAZ", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kategori-gruplari/linkUrlZA", [CategoryGroupsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/no09", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/no90", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/contentAZ", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/contentZA", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/authorAZ", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/authorZA", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/categoryAZ", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/categoryZA", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/resourcePlatformAZ", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/resourcePlatformZA", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/publishDateAZ", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/publishDateZA", [SystemNewsListPageController::class, "form"]);
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/writeTimeAZ", [SystemNewsListPageController::class, "form"]); 
/*TAMAMLANDI*/ //Route::post("/sistem-paneli/haberler/writeTimeZA", [SystemNewsListPageController::class, "form"]);

/*TAMAMLANDI*/ //Route::post("/sistem-paneli/kullanici-tipi/düzenle/{no}", [UserTypeEditPageController::class, "form"]);

/* AUTHOR PAGES FORM */
/*TAMAMLANDI*/ //Route::post("/yazar-paneli/haber/ekle", [NewsCreatePageController::class, "form"]);